### ISSUE TITLE
Consider updating FontAwesome version from 5.2.0 to 5.15.4

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/font_awesome#17] opened 2022-01-06 02:34 UTC
The current version of FontAwesome (as of 2021-01-15) is 5.15.4, but the version that's hard-coded in this module is 5.2.0. Consider either:

* Updating the hard-coded version to the most recent, or
* Adding an option setting to config to the let the user choose to stick with 5.2.0 or upgrade to a more recent version.

**Comment by ghost** [comment] 2022-01-06 02:43
Duplicate of https://github.com/backdrop-contrib/font_awesome/issues/7

**Closed as completed by ghost** 2022-01-06 02:43 UTC
Labels: duplicate

**Comment by bugfolder** [comment] 2022-01-06 03:09
Oops, yes, sorry.
